<?php /** @var $this Afterpay_Afterpay_Block_Form_Payovertime */ ?>
<div id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div id="<?php echo $this->getDetailsTemplateId() ?>"></div>
</div>

<script type="text/javascript">

    /** @require /js/Afterpay/checkout/payovertime.js */
    AfterpayM1.CheckoutForm.detailsConfiguration = <?php echo json_encode($this->getDetailsConfiguration()) ?>;

//    // render pay over time checkout option form on dom:loaded event
//    document.observe('dom:loaded', function () {
//    });
    AfterpayM1.CheckoutForm.detailsRender();

    jQuery(AfterpayM1.CheckoutForm.detailsConfiguration.creditUsedSelector).on('change', function(){
        AfterpayM1.CheckoutForm.detailsRender();
    });

</script>
