<?php /** @var $this Afterpay_Afterpay_Block_Form_Payovertime */ ?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li class="form-alt">
        <div class="instalments">
            <p class="header-text">
                <?php echo $this->__('Your payment schedule. Four interest-free payments totalling ') ?>
                <?php echo $this->getOrderTotal() ?>
            </p>
            <ul class="cost">
                <li><?php echo $this->getInstalmentAmount() ?></li>
                <li><?php echo $this->getInstalmentAmount() ?></li>
                <li><?php echo $this->getInstalmentAmount() ?></li>
                <li><?php echo $this->getInstalmentAmount() ?></li>
            </ul>
            <ul class="icon">
                <li>
                    <img src="<?php echo $this->getSkinUrl('afterpay/images/checkout/circle_1@2x.png') ?>" alt="" />
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('afterpay/images/checkout/circle_2@2x.png') ?>" alt="" />
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('afterpay/images/checkout/circle_3@2x.png') ?>" alt="" />
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('afterpay/images/checkout/circle_4@2x.png') ?>" alt="" />
                </li>
            </ul>
            <ul class="instalment">
                <li>in 2 weeks</li>
                <li>in 4 weeks</li>
                <li>in 6 weeks</li>
                <li>in 8 weeks</li>
            </ul>
        </div>
        <div class="instalment-footer">
            <p><?php echo $this->__("You'll be redirected to the Afterpay website when you proceed to checkout.") ?></p>
            <a href="http://www.afterpay.com.au/terms/" target="_blank"><?php echo $this->__('Terms & Conditions') ?></a>
        </div>
    </li>
</ul>
