<div id="afterpay-what-is-modal" style="display:none;">
    <img src="<?php echo $this->getSkinUrl('afterpay/images/ap-logo-152x31.png') ?>" alt="Afterpay" class="afterpay-logo" />
    <h3><?php echo $this->__('Buy now. Pay later. Interest-free.') ?></h3>
    <p class="partner-text"><?php echo $this->__('We have partnered with Afterpay to bring you simple, interest-free payment plans. Buy what you want today, pay when it suits you best.') ?></p>
    <ul class="afterpay-benefits">
        <li>
            <div class="image">
                <img src="<?php echo $this->getSkinUrl('afterpay/images/modal/icon_calendar.png') ?>" alt="" />
            </div>
            <div class="description">
                <h4><?php echo $this->__('Pay over time') ?></h4>
                <p><?php echo $this->__('Pay in 4 simple instalments over 8 weeks') ?></p>
            </div>
        </li>
        <li>
            <div class="image">
                <img src="<?php echo $this->getSkinUrl('afterpay/images/modal/icon_no-hidden.png') ?>" alt="" />
            </div>
            <div class="description">
                <h4><?php echo $this->__('No hidden fees') ?></h4>
                <p><?php echo $this->__('100% interest-free. No extras. No catches*.') ?></p>
            </div>
        </li>
        <li>
            <div class="image">
                <img src="<?php echo $this->getSkinUrl('afterpay/images/modal/icon_timer.png') ?>" alt="" />
            </div>
            <div class="description">
                <h4><?php echo $this->__('No card application') ?></h4>
                <p><?php echo $this->__('No lengthy application. Instant approval online.') ?></p>
            </div>
        </li>
    </ul>
    <div class="afterpay-footer">
        <h4>Simply select Afterpay at checkout.</h4>
        <a href="#" class="close-afterpay-button"><?php echo $this->__('Continue shopping') ?></a>
    </div>
    <p class="terms-and-conditions">
        <a href="http://www.afterpay.com.au/terms/" target="_blank"><?php echo $this->__('Terms & Conditions') ?></a> apply
    </p>
    <p class="late-fee-information">* If you fail to have sufficient funds available for afterpay to automatically deduct payment on due instalment dates you will be charged a late fee of $10 and if the instalment payment remains overdue, an additional $7 will be charged one week later.</p>
</div>