<span class="paypal-or"><?php echo $this->__('-OR-'); ?></span>
</li><li class="method-afterpay_onetouch">

    <h3><?php echo $this->__('Check out with Afterpay and pay over time.') ?></h3>
    <p><?php echo $this->__('Simply pay 4 fortnightly interest-free payments of %s', $this->getInstalmentAmount()) ?></p>
    <p>
        <?php echo $this->__('Use your debit or credit card, instant approval') ?>
        <a href="#afterpay-what-is-modal" class="afterpay-what-is-modal-trigger">
            <?php echo $this->__('Learn more') ?>
        </a>
    </p>
    <a href="<?php echo $this->getUrl('afterpay/onetouch') ?>" class="button btn-proceed-checkout btn-checkout">
        <?php echo $this->__('Buy now, pay later') ?>
    </a>
