<img src="<?php echo $this->getSkinUrl('afterpay/images/ap-logo-152x31.png') ?>" class="v-middle" id="afterpay-logo" />
<span id="afterpay-callout"><?php echo $this->__('Pay four interest-free payments every 2 weeks.') ?></span>
<a href="#afterpay-what-is-modal" id="what-is-afterpay-trigger">
    <?php echo $this->__('What is Afterpay?') ?>
</a>
<script>
    //<![CDATA[
    // included inline as this template is loaded through an ajax request
    jQuery('#what-is-afterpay-trigger').fancybox({
        afterShow: function() {
            jQuery('#afterpay-what-is-modal').find('.close-afterpay-button').on('click', function(event) {
                event.preventDefault();
                jQuery.fancybox.close();
            })
        }
    });
    //]]>
</script>
