<?php /** @this Afterpay_Afterpay_Block_Catalog_Installments */ ?>
<script src="<?php echo Mage::getBaseUrl('js') . 'Afterpay/Installments.js'; ?>"></script>
<script type="text/javascript">

    /** @require /js/Afterpay/Installments.js */
    AfterpayM1.Installments.config = <?php echo json_encode($this->getJsConfig()) ?>;

    // render installments amounts on dom:loaded event
    document.observe('dom:loaded', function () {
        AfterpayM1.Installments.render();
    });

    // re-render installments on every price change for configurable products
    Product.OptionsPrice.prototype.reload = Product.OptionsPrice.prototype.reload.wrap(function (callOriginal) {
        callOriginal();
        AfterpayM1.Installments.render();
    });

</script>
