<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'afterpay_afterpay_block_adminhtml_system_config_form_field_moduleversion' => '/../app/code/local/Afterpay/Afterpay/Block/Adminhtml/System/Config/Form/Field/ModuleVersion.php',
                'afterpay_afterpay_block_banner' => '/../app/code/local/Afterpay/Afterpay/Block/Banner.php',
                'afterpay_afterpay_block_catalog_installments' => '/../app/code/local/Afterpay/Afterpay/Block/Catalog/Installments.php',
                'afterpay_afterpay_block_form_abstract' => '/../app/code/local/Afterpay/Afterpay/Block/Form/Abstract.php',
                'afterpay_afterpay_block_form_beforeyoupay' => '/../app/code/local/Afterpay/Afterpay/Block/Form/Beforeyoupay.php',
                'afterpay_afterpay_block_form_card' => '/../app/code/local/Afterpay/Afterpay/Block/Form/Card.php',
                'afterpay_afterpay_block_form_payovertime' => '/../app/code/local/Afterpay/Afterpay/Block/Form/Payovertime.php',
                'afterpay_afterpay_block_info' => '/../app/code/local/Afterpay/Afterpay/Block/Info.php',
                'afterpay_afterpay_block_redirect' => '/../app/code/local/Afterpay/Afterpay/Block/Redirect.php',
                'afterpay_afterpay_exception' => '/../app/code/local/Afterpay/Afterpay/Exception.php',
                'afterpay_afterpay_helper_data' => '/../app/code/local/Afterpay/Afterpay/Helper/Data.php',
                'afterpay_afterpay_model_api_adapter' => '/../app/code/local/Afterpay/Afterpay/Model/Api/Adapter.php',
                'afterpay_afterpay_model_method_base' => '/../app/code/local/Afterpay/Afterpay/Model/Method/Base.php',
                'afterpay_afterpay_model_method_beforeyoupay' => '/../app/code/local/Afterpay/Afterpay/Model/Method/Beforeyoupay.php',
                'afterpay_afterpay_model_method_card' => '/../app/code/local/Afterpay/Afterpay/Model/Method/Card.php',
                'afterpay_afterpay_model_method_payovertime' => '/../app/code/local/Afterpay/Afterpay/Model/Method/Payovertime.php',
                'afterpay_afterpay_model_observer' => '/../app/code/local/Afterpay/Afterpay/Model/Observer.php',
                'afterpay_afterpay_model_resource_shippedapiqueue' => '/../app/code/local/Afterpay/Afterpay/Model/Resource/ShippedApiQueue.php',
                'afterpay_afterpay_model_resource_shippedapiqueue_collection' => '/../app/code/local/Afterpay/Afterpay/Model/Resource/ShippedApiQueue/Collection.php',
                'afterpay_afterpay_model_shippedapiqueue' => '/../app/code/local/Afterpay/Afterpay/Model/ShippedApiQueue.php',
                'afterpay_afterpay_model_system_config_source_apimode' => '/../app/code/local/Afterpay/Afterpay/Model/System/Config/Source/ApiMode.php',
                'afterpay_afterpay_model_system_config_source_paymentreview' => '/../app/code/local/Afterpay/Afterpay/Model/System/Config/Source/Paymentreview.php',
                'afterpay_afterpay_paymentcontroller' => '/../app/code/local/Afterpay/Afterpay/controllers/PaymentController.php',
                'apiadapterdataprovider' => '/ApiAdapterDataProvider.php',
                'apiadaptertest' => '/ApiAdapterTest.php',
                'mockfactory' => '/MockFactory.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
